# Generated by Django 4.1.1 on 2022-12-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('pronouns', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height_ft', models.IntegerField(blank=True, null=True)),
                ('height_in', models.IntegerField(blank=True, null=True)),
                ('calories_burned_today', models.IntegerField(default=0)),
                ('total_calories_burned', models.IntegerField(default=0)),
            ],
        ),
    ]
