# Generated by Django 4.1.1 on 2022-12-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_userprofile_age_pref_userprofile_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender_pref',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6),
        ),
    ]
