# Generated by Django 4.1.1 on 2022-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapi", "0004_rename_age_pref_userprofile_time_pref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="time_pref",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
