# Generated by Django 4.1.1 on 2022-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapi", "0005_alter_userprofile_time_pref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="time_pref",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
