# Generated by Django 4.1.1 on 2022-10-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_alter_userprofile_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calories_burnt_today',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_calories_burnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
