# Generated by Django 4.1.1 on 2022-10-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_alter_userprofile_calories_burnt_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='calories_burnt_today',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_calories_burnt',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='calories_burned_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
