# Generated by Django 4.1.1 on 2022-10-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_alter_userprofile_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
