# Generated by Django 4.1.1 on 2022-10-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0012_alter_userprofile_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
