# Generated by Django 4.1.1 on 2022-10-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0013_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calories_burned_today',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_calories_burned',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
