# Generated by Django 4.1.1 on 2022-10-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0014_alter_userprofile_calories_burned_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
