# Generated by Django 4.1.1 on 2022-11-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
