# Generated by Django 4.1.1 on 2022-11-06 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('pronouns', models.CharField(blank=True, max_length=30, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height_ft', models.IntegerField(blank=True, null=True)),
                ('height_in', models.IntegerField(blank=True, null=True)),
                ('calories_burned_today', models.IntegerField(blank=True, default=0, null=True)),
                ('total_calories_burned', models.IntegerField(blank=True, default=0, null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
