# Generated by Django 4.1.1 on 2022-11-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uid',
        ),
    ]
