# This is a basic workflow to help you get started with Actions

name: Tests, Test Coverage, and Style Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      
      - name: Runs Python tests
        run: python -m unittest
        
      - name: Test Coverage with Coverage.py
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage report -m
      
      - name: Checks if code follows PEP8 style guide 
        run: |
          pip install pylint
          pip install pylint-fail-under
          pylint --fail-under=8 $(git ls-files '*.py')
