# This is a basic workflow to help you get started with Actions

name: Tests, Test Coverage, and Style Check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      
      - name: Install all needed modules
        run: |
          pip install django
          pip install djangorestframework
          pip install pytest
          pip install pytest-django
          pip install coverage
          pip install pylint
          pip install pylint-fail-under
          
      - name: Checks if code follows PEP8 style guide 
        run: |
          pylint --disable=C0103,C0116,C0114,C0115,R0801,W0611,C0304,R0901,C0301,E0307,R0903,E1101,W0613,C0413 --fail-under=7 $(git ls-files '*.py')
          
      - name: Runs Python tests
        run: |
          cd backend
          cd django-test
          pytest
          
      - name: Runs Test Coverage with Coverage.py
        run: |
          cd backend
          cd django-test
          coverage run -a -m pytest
          coverage report -m --fail-under=70
